import type { Locator } from "../types";

export const BornTodayLocators = {
  filterChip: {
    xpath: "//div[@data-testid='born-today-applied-chip']",
    role: "group",
    accessibleNames: { ES: "Filtro aplicado", EN: "Applied filter" },
    dataTestId: "born-today-applied-chip",
    cssSelector: "div[data-testid='born-today-applied-chip']",
    description: "Applied filter chip",
  },
  filterChipRemove: {
    xpath: "//button[@aria-label='Remove']",
    role: "button",
    accessibleNames: { ES: "Eliminar filtro", EN: "Remove filter" },
    textContent: { ES: "Eliminar filtro", EN: "Remove filter" },
    cssSelector: "button[aria-label='Remove']",
    description: "Remove button on applied chip",
  },
  fromDayInput: {
    xpath: "//input[@data-testid='born-today-from-day']",
    role: "spinbutton",
    accessibleNames: { ES: "Día desde", EN: "From day" },
    dataTestId: "born-today-from-day",
    cssSelector: "input[data-testid='born-today-from-day']",
    description: "From date day input",
  },
  fromMonthInput: {
    xpath: "//input[@data-testid='born-today-from-month']",
    role: "spinbutton",
    accessibleNames: { ES: "Mes desde", EN: "From month" },
    dataTestId: "born-today-from-month",
    cssSelector: "input[data-testid='born-today-from-month']",
    description: "From date month input",
  },
  fromYearInput: {
    xpath: "//input[@data-testid='born-today-from-year']",
    role: "spinbutton",
    accessibleNames: { ES: "Año desde", EN: "From year" },
    dataTestId: "born-today-from-year",
    cssSelector: "input[data-testid='born-today-from-year']",
    description: "From date year input",
  },
  toDayInput: {
    xpath: "//input[@data-testid='born-today-to-day']",
    role: "spinbutton",
    accessibleNames: { ES: "Día hasta", EN: "To day" },
    dataTestId: "born-today-to-day",
    cssSelector: "input[data-testid='born-today-to-day']",
    description: "To date day input",
  },
  toMonthInput: {
    xpath: "//input[@data-testid='born-today-to-month']",
    role: "spinbutton",
    accessibleNames: { ES: "Mes hasta", EN: "To month" },
    dataTestId: "born-today-to-month",
    cssSelector: "input[data-testid='born-today-to-month']",
    description: "To date month input",
  },
  toYearInput: {
    xpath: "//input[@data-testid='born-today-to-year']",
    role: "spinbutton",
    accessibleNames: { ES: "Año hasta", EN: "To year" },
    dataTestId: "born-today-to-year",
    cssSelector: "input[data-testid='born-today-to-year']",
    description: "To date year input",
  },
  applyButton: {
    xpath: "//button[@data-testid='born-today-apply']",
    role: "button",
    accessibleNames: { ES: "Aplicar", EN: "Apply" },
    textContent: { ES: "Aplicar", EN: "Apply" },
    dataTestId: "born-today-apply",
    cssSelector: "button[data-testid='born-today-apply']",
    description: "Apply date filter button",
  },
  celebrityList: {
    xpath: "//ul[@data-testid='born-today-results']",
    role: "list",
    accessibleNames: { ES: "Resultados", EN: "Results" },
    dataTestId: "born-today-results",
    cssSelector: "ul[data-testid='born-today-results']",
    description: "Celebrity results list",
  },
  accordionToggle: {
    xpath: "//button[contains(@class,'ipc-accordion__header')]",
    role: "button",
    cssSelector: "button.ipc-accordion__header",
    description: "Filter section accordion toggle — textContent used to target a specific section (e.g. 'Birth Date')",
  },
} satisfies Record<string, Locator>;

export type BornTodayLocatorMap = typeof BornTodayLocators;
